--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Dim9999/ProjectileTrails
build-by-default: true
branches:
- master
projects:
  ProjectileTrails:
    path: ""
    icon: "icon.png"
    projectId: 6746
    lint:
      phpstan: false
...
