--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Dim9999/ArrowTrails
build-by-default: true
branches:
- master
projects:
  ArrowTrails:
    path: ""
    lint:
      phpstan: false
    icon: Icon.png
...
