---
name: ProjectileTrails
main: Fadhel\ProjectileTrails\Main
version: 2.0.0
api: 3.0.0
author: Fadhel
website: https://github.com/DimBis
description: "Spawn particles to player's projectiles if they have permissions"
permissions:
  projectiletrails.angryvillager:
    default: op
  projectiletrails.enchantment:
    default: op
  projectiletrails.explode:
    default: op
  projectiletrails.heart:
    default: op
  projectiletrails.happyvillager:
    default: op
  projectiletrails.flame:
    default: op
  projectiletrails.lava:
    default: op
  projectiletrails.lavadrip:
    default: op
  projectiletrails.portal:
    default: op
  projectiletrails.rainbowdust:
    default: op
  projectiletrails.smoke:
    default: op
  projectiletrails.water:
    default: op
  projectiletrails.waterdrip:
    default: op
...
