name: ArrowTrails
main: Fadhel\ArrowTrails\Main
version: 1.2.0
api: 3.0.0
author: Fadhel
website: https://youtube.com/c/FadhelFS
description: "Spawn particles to player's arrows if they have permissions" 
permissions:
  arrowtrails.angryvillager:
    default: op
  arrowtrails.heart:
    default: op
  arrowtrails.happyvillager:
    default: op
  arrowtrails.flame:
    default: op
  arrowtrails.lava:
    default: op
  arrowtrails.lavadrip:
    default: op
  arrowtrails.waterdrip:
    default: op
  arrowtrails.enchantment:
    default: op
